services:
  auth:
    image: quay.io/keycloak/keycloak:23.0.1
    command: start-dev
    ports:
      - "${AUTH_KEYCLOACK_PORT}:8080"
    environment:
      - KEYCLOAK_ADMIN=${AUTH_KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${AUTH_KEYCLOAK_ADMIN_PASSWORD}
