#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	  CREATE DATABASE shadow;
	  CREATE ROLE ${POSTGRAPHILE_AUTHENTICATOR_USER} WITH LOGIN PASSWORD '${POSTGRAPHILE_AUTHENTICATOR_PASSWORD}' NOINHERIT;

	  CREATE ROLE ${POSTGRAPHILE_ANON_ROLE};
	  GRANT ${POSTGRAPHILE_ANON_ROLE} TO ${POSTGRAPHILE_AUTHENTICATOR_USER};

	  CREATE ROLE "${POSTGRAPHILE_USER_ROLE}";
	  GRANT "${POSTGRAPHILE_USER_ROLE}" TO ${POSTGRAPHILE_AUTHENTICATOR_USER};

	  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRAPHILE_AUTHENTICATOR_USER};
	  GRANT ALL ON DATABASE ${POSTGRES_DB} TO ${POSTGRAPHILE_AUTHENTICATOR_USER};
	  ALTER SCHEMA public OWNER TO ${POSTGRAPHILE_AUTHENTICATOR_USER};

	  CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
	  CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
	  CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
	  CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


EOSQL
