#!/bin/bash
set -e

if [[ "$NODE_ENV" == "development" ]]; then
	echo -e "\nPlaying dev script :\n"
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		  CREATE DATABASE shadow;
	EOSQL
fi

echo -e "\nPlaying script : \n"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	  CREATE ROLE ${DATABASE_OWNER} WITH LOGIN PASSWORD '${DATABASE_OWNER_PASSWORD}' SUPERUSER;
	  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DATABASE_OWNER};
	  GRANT ALL ON DATABASE ${POSTGRES_DB} TO ${DATABASE_OWNER};

	  CREATE ROLE ${AUTHENTICATOR_ROLE} WITH LOGIN PASSWORD '${AUTHENTICATOR_PASSWORD}' NOINHERIT;

	  CREATE ROLE ${ANON_ROLE} nologin;
	  GRANT ${ANON_ROLE} TO ${AUTHENTICATOR_ROLE};

	  CREATE ROLE ${PERSON_ROLE} nologin;
	  GRANT ${PERSON_ROLE} TO ${AUTHENTICATOR_ROLE};
EOSQL
