#!/bin/bash
set -e

# Remove alter schema public

if [[ "$NODE_ENV" == "development" ]]; then
	echo -e "\nPlaying dev script :\n"
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		  CREATE DATABASE shadow;
	EOSQL
fi

echo -e "\nPlaying script : \n"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	  CREATE ROLE ${DATABASE_OWNER} WITH LOGIN PASSWORD '${DATABASE_OWNER_PASSWORD}' SUPERUSER;
	  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DATABASE_OWNER};
	  GRANT ALL ON DATABASE ${POSTGRES_DB} TO ${DATABASE_OWNER};

	  CREATE ROLE ${POSTGRAPHILE_AUTHENTICATOR_ROLE} WITH LOGIN PASSWORD '${POSTGRAPHILE_AUTHENTICATOR_PASSWORD}' NOINHERIT;

	  CREATE ROLE ${POSTGRAPHILE_ANON_ROLE};
	  GRANT ${POSTGRAPHILE_ANON_ROLE} TO ${POSTGRAPHILE_AUTHENTICATOR_ROLE} nologin;

	  CREATE ROLE ${POSTGRAPHILE_PERSON_ROLE};
	  GRANT ${POSTGRAPHILE_PERSON_ROLE} TO ${POSTGRAPHILE_AUTHENTICATOR_ROLE} nologin;
EOSQL
